### ISSUE TITLE
Hello, is it possible to change the training?

### ISSUE THREAD

**Issue by vpreparate** [timendum/ciccio#1]
you can change the training only by folder ok I didn’t fully understand the essence of this training... I have 5k excerpts but they are all perfect I understand that they should be in the ok directory

**Comment by timendum** [comment]
This tool separates ok excerpts from not-ok excerpts that are in one file.

So you should have ok excerpts but also not-ok excerpts.

In my example I have one mp3 with speech and music, speech is ok and music is not-ok.  
I split the original mp3 in two folders: speech in ok and music in the other, than I can run the training.

I hope it helps.
